### PR TITLE
reexported frost core internals

### PR DESCRIPTION
**Pull request by 0xfinetuned**
reexport frost core with internals features in order to verify single signature shares before aggregation.

### CODE REVIEW

**Comment by 0xfinetuned** [comment]
@zebra-lucky we are implementing ROAST on top of this crate and need to verify signature shares separately from aggregation.
Would love to hear your thoughts about this

**Comment by conduition** [comment]
If you need the internal features of the `frost_core` crate, why not just do this in your project?

```
cargo add frost_core --features internals
```

**Comment by conduition** [comment]
Also, have you tried using [the `cheater-detection` feature in `frost-core`?](https://github.com/ZcashFoundation/frost/blob/3ebe7a1c9d407de0875f1a68bde0aa019ddd45ab/frost-core/src/lib.rs#L598-L644)

**Comment by zebra-lucky** [comment]
@0xfinetuned, do you still need changes in https://github.com/zebra-lucky/frost/pull/6 after recommendation of use internals feature?

**Comment by ArchSpaceman** [comment]
Hello, thanks for the prompt reply, we already tried re-importing frost-core, but we get type mismatches between frost-core and frost-secp-256k1 when using the internals.

**Comment by zebra-lucky** [comment]
Hello! Possibly code in the tests can help do casting of types between core-curve crates.

**Comment by ArchSpaceman** [comment]
> Also, have you tried using [the `cheater-detection` feature in `frost-core`?](https://github.com/ZcashFoundation/frost/blob/3ebe7a1c9d407de0875f1a68bde0aa019ddd45ab/frost-core/src/lib.rs#L598-L644)

Yes cheater detection is already enabled, we can detect malicious participants during aggregation but we're still struggling to verify signature shares against verifying shares when the remaining participants haven't issued a signature yet.

I'll be re-trying the casting between the crates and keep you updated !

**Comment by conduition** [comment]
If you're getting version mismatches, your `Cargo.lock` will probably show you why. If your curve-specific frost crate (e.g. `frost_secp256k1_tr`) depends on `frost_core` version `X` but your project depends on `frost_core` version `Y`, then Rust will complain because `frost_core@X` and `frost_core@Y` are effectively different crates to the compiler. You'll want to ensure both your crate and your curve-specific frost crate resolve to the same `frost_core` version

**Comment by ArchSpaceman** [comment]
> If you're getting version mismatches, your `Cargo.lock` will probably show you why. If your curve-specific frost crate (e.g. `frost_secp256k1_tr`) depends on `frost_core` version `X` but your project depends on `frost_core` version `Y`, then Rust will complain because `frost_core@X` and `frost_core@Y` are effectively different crates to the compiler. You'll want to ensure both your crate and your curve-specific frost crate resolve to the same `frost_core` version

Thanks for the heads up ! Apparently the current PR is behind by a couple commits, I think that's what was causing the type mismatch. To address this we had to reimport frost-core from the branch directly and not rely on the registry : 
`frost-core = { git="https://github.com/zebra-lucky/frost.git", branch = "add-secp256k1-tr", version = "1.0.0", features = ["internals"] }`

I think this won't be an issue once the PR is merged upstream.

We appreciate your help and your contributions !

**Pull request closed without merging**
