### PR TITLE
encapsulate BIP341 tapscript commitment in new SigningTarget type 

### PR DESCRIPTION
**Pull request by conduition**
I added the SigningTarget type, which encapsulates both the message to be signed, and also the tapscript merkle root which the signature should commit to. This allows a FROST group to dynamically select what taproot tweak they would like to commit their signatures to, and to optionally elect not to commit to any tweak at all if desired.

Notable breaking changes between this and `master`:
- This changes the JSON serializations of the `SigningPackage` structs for existing ciphersuites, but not the binary serializations.
- Instead of `SigningPackage::message` returning `&Vec<u8>`, it now returns `&[u8]`. We _could_ change it to return `&Vec<u8>` for compatibility if needed but I think most downstream users will be ok with `&[u8]`.

### CODE REVIEW

**Comment by conduition** [comment]
See [this comment](https://github.com/ZcashFoundation/frost/pull/584#issuecomment-1974921674) for usage examples.

**Comment by conduition** [comment]
~Tests are failing, investigating~ EDIT: fixed

**Comment by zebra-lucky** [comment]
Looking to changes.

**Comment by zebra-lucky** [comment]
Looks really good. Thank you, your help is invaluable!
I'm not maintainer of this crate also and has very low
productivity for now, but how you write -- i'm trying to
run upstream PR to production.

p.s.: found one typo in docstring, i'm will fix it and then merge:
`Return the effective signing key` -> `Return the effective verifying key`,
for `VerifyingKey.effective_key`

**Pull request merged**
